const API_BASE_URL_DEVELOPMENT = 'http://localhost:5210';
const API_BASE_URL_PRODUCTION = 'http://appname.azurewebsites.net';

const ENDPOINTS = {
    AUTHENTICATION: 'api/Auth',
    BING_ENTRIES: 'api/BingSearchTerms',
    GOOGLE_ENTRIES: 'api/GoogleSearchTerms',
    LEAD_ENTRIES: 'api/LeadEntries',
    ORDER_ENTRIES: 'api/OrderEntries',

    GET_ENTRY_BY_ID: 'get-entry-by-id',

    LOGIN_ENTRIES: 'api/LoginEntries'
};

const development = {
    API_URL_AUTHENTICATION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.AUTHENTICATION}`,
    API_URL_BING_ENTRIES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.BING_ENTRIES}`,
    API_URL_GOOGLE_ENTRIES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GOOGLE_ENTRIES}`,
    API_URL_LEAD_ENTRIES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LEAD_ENTRIES}`,
    API_URL_ORDER_ENTRIES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.ORDER_ENTRIES}`,
    API_URL_BASE: `${API_BASE_URL_DEVELOPMENT}`,

    API_URL_GET_ENTRY_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ENTRY_BY_ID}`,

    API_URL_LOGIN_ENTRIES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN_ENTRIES}`
};

const production = {
    API_URL_AUTHENTICATION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.AUTHENTICATION}`,
    API_URL_BING_ENTRIES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.BING_ENTRIES}`,
    API_URL_GOOGLE_ENTRIES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GOOGLE_ENTRIES}`,
    API_URL_LEAD_ENTRIES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.LEAD_ENTRIES}`,
    API_URL_ORDER_ENTRIES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.ORDER_ENTRIES}`,
    API_URL_BASE: `${API_BASE_URL_PRODUCTION}`,

    API_URL_GET_ENTRY_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ENTRY_BY_ID}`,

    API_URL_LOGIN_ENTRIES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.LOGIN_ENTRIES}`
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;